//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Product</summary>
	[PublishedContentModel("product")]
	public partial class Product : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "product";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Product(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Product, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// Pictures
		///</summary>
		[ImplementPropertyType("pictures")]
		public IEnumerable<IPublishedContent> Pictures
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("pictures"); }
		}

		///<summary>
		/// Price
		///</summary>
		[ImplementPropertyType("price")]
		public decimal Price
		{
			get { return this.GetPropertyValue<decimal>("price"); }
		}

		///<summary>
		/// ProductBrand
		///</summary>
		[ImplementPropertyType("productBrand")]
		public IPublishedContent ProductBrand
		{
			get { return this.GetPropertyValue<IPublishedContent>("productBrand"); }
		}

		///<summary>
		/// ProductColor
		///</summary>
		[ImplementPropertyType("productColor")]
		public IEnumerable<IPublishedContent> ProductColor
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("productColor"); }
		}

		///<summary>
		/// ProductName
		///</summary>
		[ImplementPropertyType("productName")]
		public string ProductName
		{
			get { return this.GetPropertyValue<string>("productName"); }
		}

		///<summary>
		/// ProductSizes
		///</summary>
		[ImplementPropertyType("productSizes")]
		public IEnumerable<IPublishedContent> ProductSizes
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("productSizes"); }
		}
	}
}
